---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: ./setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: ./setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Disable default apache ssl config
  command: >
    mv {{apache_conf_path}}/ssl.conf {{apache_conf_path}}/ssl.conf.disabled
    creates={{apache_conf_path}}/ssl.conf.disabled
  notify: restart apache
  sudo: yes

- name: Add apache vhosts configuration.
  template: >
    src=vhosts.conf.j2
    dest={{ apache_conf_path }}/vhosts.conf
    owner=root group=root mode=644
  notify: restart apache
  when: apache_create_vhosts
  sudo: yes

- name: Ensure Apache is started and enabled on boot.
  service: >
    name={{ apache_daemon }}
    state=started
    enabled=yes
  sudo: yes
